/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagemopencv;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import static javafx.scene.paint.Color.color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfRect;
import org.opencv.core.Point;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.core.Size;
import org.opencv.imgproc.Imgproc;
import org.opencv.objdetect.CascadeClassifier;
import org.opencv.videoio.VideoCapture;

/**
 *
 * @author Poseidom
 */
public class ReconhecimentoemcamerasEvideos extends javax.swing.JFrame {

    /**
     * Creates new form webcam
     */
    public ReconhecimentoemcamerasEvideos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        
        ReconhecimentoemcamerasEvideos janela = new ReconhecimentoemcamerasEvideos();
        janela.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        janela.setSize(1600,1024);
        janela.setVisible(true);
        janela.mostrarVideo();
        
       
    }
    
    
    
    public void mostrarVideo(){
        
        Mat video = new Mat();
        VideoCapture captura = new VideoCapture("src\\imagemopencv\\transito.mp4");
   
        
       
        if(captura.read(video)){
           
            while(true){
                captura.read(video);
                if(!video.empty()){
                    
                    setSize(video.width()+30, video.height()+70);
                    
                    Mat imagemcolorida = video;
                    Mat imagemcinza = new Mat();
                    Imgproc.cvtColor(imagemcolorida, imagemcinza, Imgproc.COLOR_BGR2GRAY);
                    CascadeClassifier classificador = new CascadeClassifier("src\\CASCATES\\cars.xml");
                    
                    MatOfRect facesdetectadas = new MatOfRect();
                    classificador.detectMultiScale(imagemcinza, facesdetectadas,
                                1.09,//scale factor
                                3, //minneighbors
                                0,//flags
                                new Size(30,30), //MinSize
                                new Size(800,800)); //MaxSize;
                    
                    for(Rect rect: facesdetectadas.toArray()){
                        
                        Imgproc.rectangle(imagemcolorida, 
                                new Point(rect.x,rect.y),
                                new Point(rect.x+ rect.width, rect.y+rect.height),
                                new Scalar(0,0,255),2);
                        
                      
                       
                    }
                    
      
                    
                    
                    
                    BufferedImage imagemnew = new UTILITARIOS().convertMatToImage(video);
                   
                    jPanel1.setSize(1280, 720);
                    Graphics g = jPanel1.getGraphics();
                    
                    g.drawImage(imagemnew, 10, 10, imagemnew.getWidth(), imagemnew.getHeight(),null);
                    
                }
                
            }
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
